version: 0.0
os: linux
files:
  - source: src
    destination: /var/www/html

# permissions:
#   - object: /opt/tomcat/bin
#     pattern: "*.sh"
#     owner: root
#     group: root
#     mode: 755
#     type:
#       - file

hooks:
  # ApplicationStop:
  #   - location: script/SuspandedScaling.sh
  #     timeout: 60
  #     runas: root
  #   - location: script/EC2Standby.sh
  #     timeout: 180
  #     runas: root

  BeforeInstall:
    - location: script/StopService.sh
      timeout: 180
    - location: script/EarseApp.sh
      timeout: 120

  # AfterInstall:

  ApplicationStart:
    - location: script/StartService.sh
      timeout: 300

  ValidateService:
    - location: script/VerifyService.sh
      timeout: 60
    # - location: script/EC2ExitStandby.sh
    #   timeout: 60
    #   runas: root
    # - location: script/ResumeScaling.sh
    #   timeout: 60
    #   runas: root
