version: 0.0
os: linux
files:
  - source: src
    destination: /var/www/html

# permissions:
#   - object: /opt/tomcat/bin
#     pattern: "*.sh"
#     owner: root
#     group: root
#     mode: 755
#     type:
#       - file

hooks:
  ApplicationStop:
    - location: script/deregister_from_elb.sh
      timeout: 60
      runas: root
    - location: script/stop-service.sh
      timeout: 180

  BeforeInstall:
    # - location: script/install_dependencies
    #   timeout: 300
    #   runas: root

    - location: script/earse-application.sh
      timeout: 120

  # AfterInstall:

  ApplicationStart:
    - location: script/start-service.sh
      timeout: 300
    - location: script/register_with_elb.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: script/verify-service.sh
      timeout: 60
